import Breadcrumb from "@/components/breadcrumb";
import Layout from "@/components/layout";
import Links from "@/components/links";
import site from "@/data/site";
import Link from "next/link";

export default function About() {
  return (
    <Layout
      metadata={{
        title: `About ${site.title}`,
        description: site.description,
        metaType: "article",
      }}
      hasFooter={false}
    >
      <Breadcrumb head={site.title} item={"About"} linked={false} />
      <h3 className="mt-4">
        <strong>About</strong>
      </h3>

      <main className="mt-4">
        <p>
          <strong>From the Creator</strong>
        </p>
        <p>
          PH Bird News is a fully automated artificial intelligence-powered news
          feed bringing you the latest birding reports from around the
          Philippines. Running daily from morning to midnight, articles are
          published hourly and driven by public data from{" "}
          <a href="https://ebird.org/">eBird</a>, an online database of bird
          distribution and abundance.
        </p>

        <p>
          An <Link href="/subscribe">email digest</Link> is sent to subscribers{" "}
          daily at noon.
        </p>

        <p>
          <strong>Disclaimers and Attributions</strong>
        </p>
        <p>
          All reports published on this site have been generated by an AI model
          with little to no human intervention and are intended for general
          information and entertainment purposes. The reports are created using
          1) checklist data available through the eBird platform, and 2) an
          evolving prompt optimized for straightforwardness and reliance on
          user-submitted information.{" "}
          <a href="https://docs.google.com/document/d/15BpMeo4ewtDDcmtF95YbSrj0J3Kj8Z7264AWuSBKRPI/edit?tab=t.0">
            I have made the prompt public
          </a>{" "}
          for anyone curious about it.
        </p>
        <p>
          eBird facilitates{" "}
          <a href="https://support.ebird.org/en/support/solutions/articles/48001078113-ebird-data-privacy-and-data-use">
            open sharing of observations
          </a>{" "}
          for the benefit of birders and conservationists and makes their data
          available for non-commercial use. To the best of my understanding of
          the{" "}
          <a href="https://www.birds.cornell.edu/home/ebird-data-access-terms-of-use/">
            eBird Data Access Terms of Use
          </a>
          , this project&apos;s is a legitimate use case. However, it is not
          endorsed by eBird in any way. I welcome all feedback regarding this
          project&apos;s use of data to ensure accordance with eBird&apos;s
          latest terms.
        </p>
        <p>
          Finally, generative AI being what it is, inaccuracies and whimsical
          embellishments are to be expected at any moment, especially in less
          recent reports, but hopefully benign and amusing. To mitigate this,
          articles are ephemeral and stay publicly listed for only 72 hours. I
          am always experimenting to get the best possible results from the AI
          model.
        </p>

        <p>
          <strong>Intent</strong>
        </p>
        <p>
          I hope the site becomes a fun way to stay up-to-date on goings-on in
          the small birding world of the Philippines and encourages more eBird
          submissions.
        </p>
        <p>
          This is a non-commercial project built firstly for my own amusement,
          but should it generate enough interest, potential future improvements
          are:
        </p>
        <ul>
          <li>Human editors</li>
          <li>Photos</li>
        </ul>
        <p>
          The site is currently in a &quot;semi-public beta&quot; phase and
          discourages search engines from indexing it.
        </p>
        <p>
          If you like what you see or have any comments,{" "}
          <a href={`mailto:${site.mailto}`}>contact me</a>.
        </p>
      </main>

      <Links />
    </Layout>
  );
}
