import Link from "next/link";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function Attribution(props: any) {
  return (
    <section {...(props as object)}>
      This report was generated by a large language model using data sourced
      from <a href="https://ebird.org">eBird</a>, an online database of bird
      distribution and abundance. <Link href="/about">Read more</Link>.
    </section>
  );
}
